# Generated by Django 5.1.3 on 2024-11-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CtfWriteup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('competetion', models.CharField(max_length=50)),
                ('point_count', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=300)),
                ('hints', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
