# Generated by Django 5.1.3 on 2024-11-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctfwriteup',
            name='body_text',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='ctfwriteup',
            name='code_snippets',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='ctfwriteup',
            name='image',
            field=models.ImageField(default='apples', upload_to=''),
            preserve_default=False,
        ),
    ]
