# Generated by Django 5.1.3 on 2024-11-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ctfwriteup_body_text_ctfwriteup_code_snippets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctfwriteup',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='ctfwriteup',
            name='code_snippets',
        ),
        migrations.AddField(
            model_name='ctfwriteup',
            name='markdown_body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ctfwriteup',
            name='description',
            field=models.TextField(),
        ),
    ]
