# Generated by Django 5.1.3 on 2024-11-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ctfwriteup_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctfwriteup',
            old_name='competetion',
            new_name='competition',
        ),
    ]
