# Generated by Django 5.1.3 on 2024-11-25 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_competetion_ctfwriteup_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctfwriteup',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 25)),
            preserve_default=False,
        ),
    ]
