# Generated by Django 5.1.3 on 2024-11-26 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ctfwriteup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctfwriteup',
            name='image',
        ),
        migrations.CreateModel(
            name='CtfImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ctf_images/')),
                ('writeup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.ctfwriteup')),
            ],
        ),
    ]
