# Generated by Django 5.1.3 on 2024-11-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_ctfwriteup_markdown_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctfimage',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='ctfwriteup',
            name='markdown_body',
            field=models.FileField(upload_to=models.CharField(max_length=50)),
        ),
    ]
