# Generated by Django 5.1.4 on 2025-01-17 00:39

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_ctfimage_image_alter_ctfwriteup_markdown_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctfimage',
            name='image',
            field=models.ImageField(upload_to=app.models.writeup_image_upload_path),
        ),
        migrations.AlterField(
            model_name='ctfwriteup',
            name='markdown_body',
            field=models.TextField(),
        ),
    ]
